version: '3.4'

services:
  transactioneventapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - TransactionStoreConnectionStringCsv=
      - ShareName=
    ports:
      - "32769:80"
      - "32768:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro